"""
Django settings for fivourr project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qy0qocibv#8_)k09z*s#c2sf0l-@t-em94b49!4fcput4l66nx'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = False
ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "template_helpers",
    'mainApp',
    'crispy_forms',
    'rest_framework',
    'API',
    'AdminPanel',
    "ChatApp",
    'rest_framework.authtoken',
    'mathfilters',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fivourr.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fivourr.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Dhaka'

USE_I18N = True

USE_L10N = True

USE_TZ = True




STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')


STATICFILES_DIRS = [
   os.path.join(BASE_DIR, 'static'),
]



# MEDIA URLS

MEDIA_URL = "/media/"
# MEDIA_ROOT = '/home/marketage/public_html/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, '/home/marketage/public_html/media/')

# ADMIN_MEDIA_PREFIX = '/static/admin/'

# LOGIN_REDIRECT_URL = '/admin'
# LOGIN_URL = '/admin/login/'



# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Stripe Credentials

STRIPE_SECRET_KEY = 'sk_test_51JQ4uaFZa2c48QIFX0WiBvefRanJXwRtpNEVftcFS9qRWe9lJYzNNX0aoHItroORU3ZkFZxviTuUxN85YWvVygkV00GbEz27rG'
STRIPE_PUBLISHABLE_KEY = 'pk_test_51JQ4uaFZa2c48QIFKlw5aHZDFyyKxIbgbuY0BpDiDC3vZqEMbTei1eit7Z74oS9hiI2qOVp9oGgBmuATnidOnBTq00BNM14e59'

# SMTP COnfiguration


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'mail.marketage.io'
EMAIL_PORT = 465
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True
EMAIL_HOST_USER = 'admin@marketage.io'
EMAIL_HOST_PASSWORD = 'marketage123'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'mail.privateemail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# # EMAIL_USE_SSL = True
# # EMAIL_HOST_USER = 'noreply@marketage.io'
# EMAIL_HOST_USER = 'noreply@marketagemail.com'
# EMAIL_HOST_PASSWORD = 'Marketage123'
# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER



## For GMAIL


# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'gmail.com'
# # EMAIL_USE_TLS = True
# EMAIL_USE_SSL = True
# EMAIL_PORT = 465
# EMAIL_HOST_USER = 'noreply.marketage@gmail.com'
# EMAIL_HOST_PASSWORD = 'Marketage123'


