# Generated by Django 3.2.6 on 2021-09-12 10:55

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerPostRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postrequest_title', models.CharField(max_length=220, null=True, unique=True)),
                ('description', models.TextField(null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='images/')),
                ('budget', models.IntegerField()),
                ('post_status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('RESERVED', 'RESERVED')], default='ACTIVE', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=120, unique=True)),
                ('icon', models.FileField(null=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg'])])),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('address', models.TextField(null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('due_date', models.DateField(null=True)),
                ('order_status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('LATE', 'LATE'), ('COMPLETED', 'COMPLETED'), ('DELIVERED', 'DELIVERED'), ('CANCELLED', 'CANCELLED'), ('ON REVIEW', 'ON REVIEW')], default='ACTIVE', max_length=200)),
                ('is_complete', models.BooleanField(default=False, null=True)),
                ('is_cancel', models.BooleanField(default=False, null=True)),
                ('on_review', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DummyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default=None, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='FileFormats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_title', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='LandingSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='MainLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_img', models.ImageField(upload_to='logos/')),
            ],
        ),
        migrations.CreateModel(
            name='NumberOfPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NumberOfPlugins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('offer_title', models.CharField(max_length=240)),
                ('seo_title', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('offer_video', models.FileField(blank=True, null=True, upload_to='images/')),
                ('document', models.FileField(null=True, upload_to='files/')),
                ('description', models.TextField()),
                ('is_popular', models.BooleanField(default=False, null=True)),
                ('pop_web', models.BooleanField(blank=True, default=False, null=True)),
                ('is_pro', models.BooleanField(default=False, null=True)),
                ('click', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('impressions', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('order_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('cancellation', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('offer_status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('PENDING APPROVAL', 'PENDING APPROVAL'), ('REQUIRED MODIFICATION', 'REQUIRED MODIFICATION'), ('DENIED', 'DENIED'), ('PAUSED', 'PAUSED')], default='ACTIVE', max_length=200, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.category')),
                ('extra_images', models.ManyToManyField(to='mainApp.ExtraImage')),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_title', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=90)),
                ('discount_amount', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='SecondarySlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=120, unique=True)),
                ('sub_title', models.CharField(max_length=120)),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('sub_title', models.CharField(max_length=120, unique=True)),
                ('sub_img', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='WithDrawPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=220, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WithDrawModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdraw_date', models.DateTimeField(default=datetime.datetime.now)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('on_review', models.BooleanField(default=True, null=True)),
                ('is_approved', models.BooleanField(default=False, null=True)),
                ('method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.withdrawpaymentmethod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SendOfferModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_offer_slug', models.SlugField(max_length=200, null=True, unique=True)),
                ('offer_letter', models.TextField(null=True)),
                ('offered_price', models.PositiveIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_offer_buyer', to=settings.AUTH_USER_MODEL)),
                ('buyer_post_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_post_request', to='mainApp.buyerpostrequest')),
                ('delivery_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_offer_delivery_time', to='mainApp.deliverytime')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_offer_seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SellerSubmit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_field', models.FileField(null=True, upload_to='files/')),
                ('submit_date', models.DateField(auto_now_add=True, null=True)),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout', to='mainApp.checkout')),
            ],
        ),
        migrations.CreateModel(
            name='SellerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateField(default=datetime.datetime.now, null=True)),
                ('contact_no', models.CharField(max_length=15, null=True)),
                ('profile_picture', models.ImageField(null=True, upload_to='images/')),
                ('level', models.IntegerField(blank=True, default=0)),
                ('wallet', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.city')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewSellerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField(default=0)),
                ('review_ield', models.TextField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_seller', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.offer')),
                ('rate_seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.rating')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('package_desc', models.TextField(null=True)),
                ('is_responsive_basic', models.BooleanField(blank=True, default=False, null=True)),
                ('is_responsive_standard', models.BooleanField(blank=True, default=False, null=True)),
                ('is_responsive_premium', models.BooleanField(blank=True, default=False, null=True)),
                ('setup_payment', models.BooleanField(blank=True, default=False, null=True)),
                ('will_deploy', models.BooleanField(blank=True, default=False, null=True)),
                ('is_compitable', models.BooleanField(blank=True, default=False, null=True)),
                ('provide_vector', models.BooleanField(blank=True, default=False, null=True)),
                ('is_3dmockup', models.BooleanField(blank=True, default=False, null=True)),
                ('is_high_res_for_basic', models.BooleanField(blank=True, default=False, null=True)),
                ('is_high_res_for_standard', models.BooleanField(blank=True, default=False, null=True)),
                ('is_high_res_for_premium', models.BooleanField(blank=True, default=False, null=True)),
                ('will_sourcefile_for_basic', models.BooleanField(blank=True, default=False, null=True)),
                ('will_sourcefile_for_standard', models.BooleanField(blank=True, default=False, null=True)),
                ('will_sourcefile_for_premium', models.BooleanField(blank=True, default=False, null=True)),
                ('is_campaign_optimization', models.BooleanField(blank=True, default=False, null=True)),
                ('management_duration', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15')], max_length=120, null=True)),
                ('video_length', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('will_embedded_sub', models.BooleanField(blank=True, default=False, null=True)),
                ('is_transactioable', models.BooleanField(blank=True, default=False, null=True)),
                ('is_translated', models.BooleanField(blank=True, default=False, null=True)),
                ('will_srt_logo', models.BooleanField(blank=True, default=False, null=True)),
                ('will_add_logo', models.BooleanField(blank=True, default=False, null=True)),
                ('provide_pdf', models.BooleanField(blank=True, default=False, null=True)),
                ('max_data', models.CharField(blank=True, max_length=450, null=True)),
                ('provide_excel', models.BooleanField(blank=True, default=False, null=True)),
                ('delivery_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.deliverytime')),
                ('num_of_pages_for_basic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='num_of_pages_for_basic', to='mainApp.numberofpage')),
                ('num_of_pages_for_premium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='num_of_pages_for_premium', to='mainApp.numberofpage')),
                ('num_of_pages_for_standard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='num_of_pages_for_standard', to='mainApp.numberofpage')),
                ('revision_basic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_basic', to='mainApp.revision')),
                ('revision_premium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_premium', to='mainApp.revision')),
                ('revision_standard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_standard', to='mainApp.revision')),
                ('supported_formats', models.ManyToManyField(blank=True, to='mainApp.FileFormats')),
            ],
        ),
        migrations.CreateModel(
            name='OfferManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.offer')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.package')),
            ],
        ),
        migrations.CreateModel(
            name='OfferFavoriteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_Favorite', models.BooleanField(default=False)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.offer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='packages',
            field=models.ManyToManyField(through='mainApp.OfferManager', to='mainApp.Package'),
        ),
        migrations.AddField(
            model_name='offer',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.services'),
        ),
        migrations.AddField(
            model_name='offer',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.subcategory'),
        ),
        migrations.AddField(
            model_name='offer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ChildSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_slug', models.SlugField()),
                ('child_title', models.CharField(max_length=220)),
                ('child_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('parent_subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.subcategory')),
            ],
        ),
        migrations.AddField(
            model_name='checkout',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.offermanager'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checkout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CategoryInterestedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_interested', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='subcategory',
            field=models.ManyToManyField(blank=True, to='mainApp.Subcategory'),
        ),
        migrations.AddField(
            model_name='buyerpostrequest',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.category'),
        ),
        migrations.AddField(
            model_name='buyerpostrequest',
            name='delivery_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.deliverytime'),
        ),
        migrations.AddField(
            model_name='buyerpostrequest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
