# Generated by Django 3.2.6 on 2021-09-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='extra_images',
            field=models.ManyToManyField(blank=True, to='mainApp.ExtraImage'),
        ),
    ]
