# Generated by Django 3.2.6 on 2021-09-18 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_supportcategorymodel_supportmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='child_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.childsubcategory'),
        ),
    ]
