# Generated by Django 3.2.6 on 2021-09-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_offer_child_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childsubcategory',
            name='parent_subcategory',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='child_subcategory',
            field=models.ManyToManyField(blank=True, to='mainApp.ChildSubcategory'),
        ),
    ]
