# Generated by Django 3.2.6 on 2021-09-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20210918_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childsubcategory',
            name='child_slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='childsubcategory',
            name='child_title',
            field=models.CharField(max_length=220, null=True, unique=True),
        ),
    ]
