# Generated by Django 3.2.6 on 2021-09-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_auto_20210918_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='slug',
            field=models.SlugField(max_length=120, null=True, unique=True),
        ),
    ]
