# Generated by Django 3.2.6 on 2021-09-21 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0008_exammodel_examsubject_qustionmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewseller',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='reviewseller',
            name='user',
        ),
        migrations.AddField(
            model_name='reviewseller',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewseller',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.checkout'),
        ),
        migrations.AddField(
            model_name='reviewseller',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_seller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewseller',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
