# Generated by Django 3.2.6 on 2021-09-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_auto_20210921_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rate_amount',
            field=models.IntegerField(default=0),
        ),
    ]
