# Generated by Django 3.2.6 on 2021-09-21 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_checkout_rated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='is_pro',
        ),
    ]
