# Generated by Django 3.2.6 on 2021-09-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_remove_offer_is_pro'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_pro',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
