# Generated by Django 3.2.6 on 2021-09-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_offer_is_pro'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleraccount',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='selleraccount',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selleraccount',
            name='is_professional',
            field=models.BooleanField(default=False),
        ),
    ]
