# Generated by Django 3.2.6 on 2021-09-21 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_auto_20210921_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selleraccount',
            name='is_premium',
        ),
    ]
