# Generated by Django 3.2.6 on 2021-09-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_remove_selleraccount_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
