# Generated by Django 3.2.6 on 2021-09-22 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_offer_is_premium'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumOfferPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkg_title', models.CharField(max_length=220)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PremiumOfferPackageCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_id', models.CharField(max_length=220)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainApp.offer')),
                ('pkg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.premiumofferpackage')),
            ],
        ),
    ]
