# Generated by Django 3.2.6 on 2021-09-23 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0017_premiumofferpackage_premiumofferpackagecheckout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumofferpackagecheckout',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainApp.offer'),
        ),
        migrations.AlterField(
            model_name='premiumofferpackagecheckout',
            name='pkg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.premiumofferpackage'),
        ),
    ]
