# Generated by Django 3.2.6 on 2021-09-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0018_auto_20210923_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumofferpackagecheckout',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
