# Generated by Django 3.2.6 on 2021-09-23 05:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0019_premiumofferpackagecheckout_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumofferpackagecheckout',
            name='addresss',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='premiumofferpackagecheckout',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='premiumofferpackagecheckout',
            name='first_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='premiumofferpackagecheckout',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
