# Generated by Django 3.2.6 on 2021-09-23 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0020_auto_20210923_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg'])]),
        ),
    ]
