# Generated by Django 3.2.6 on 2021-09-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0021_alter_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumofferpackagecheckout',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ACTIVE', 'ACTIVE'), ('EXPIRED', 'EXPIRED')], max_length=220, null=True),
        ),
    ]
