# Generated by Django 3.2.6 on 2021-09-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0022_premiumofferpackagecheckout_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumofferpackagecheckout',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='premiumofferpackagecheckout',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ACTIVE', 'ACTIVE'), ('EXPIRED', 'EXPIRED')], default='PENDING', max_length=220, null=True),
        ),
    ]
