# Generated by Django 3.2.6 on 2021-09-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0023_auto_20210923_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumofferpackage',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
