# Generated by Django 3.2.6 on 2021-09-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0024_premiumofferpackage_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawmodel',
            name='stat',
            field=models.CharField(choices=[('ON REVIEW', 'ON REVIEW'), ('REJECTED', 'REJECTED'), ('CLEARED', 'CLEARED')], max_length=220, null=True),
        ),
    ]
