# Generated by Django 3.2.6 on 2021-09-27 04:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0025_withdrawmodel_stat'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerSubjectChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('exam_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.examsubject')),
            ],
        ),
    ]
