# Generated by Django 3.2.6 on 2021-09-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0030_alter_qustionmodel_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubject',
            name='examsubject_title',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
