# Generated by Django 3.2.6 on 2021-09-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0031_examsubject_examsubject_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examsubject',
            name='category',
        ),
        migrations.RemoveField(
            model_name='examsubject',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='examsubject',
            name='examsubject_title',
        ),
        migrations.RemoveField(
            model_name='examsubject',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='examsubject',
            name='title',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.DeleteModel(
            name='SellerSubjectChoice',
        ),
    ]
