# Generated by Django 3.2.6 on 2021-09-28 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0032_auto_20210927_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiumofferpackagecheckout',
            name='tran_id',
        ),
    ]
