# Generated by Django 3.2.6 on 2021-10-05 06:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0034_examsubject_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammodel',
            name='attachement',
            field=models.FileField(upload_to='images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'pdf', 'html'])]),
        ),
    ]
