# Generated by Django 3.2.6 on 2021-10-05 06:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0036_alter_exammodel_attachement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammodel',
            name='attachement',
            field=models.FileField(upload_to='images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
    ]
