# Generated by Django 3.2.6 on 2021-10-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0039_alter_exammodel_attachement'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleraccount',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
