# Generated by Django 3.2.6 on 2021-10-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0040_selleraccount_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleraccount',
            name='is_ban',
            field=models.BooleanField(default=False),
        ),
    ]
