# Generated by Django 3.2.6 on 2021-10-05 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0041_selleraccount_is_ban'),
    ]

    operations = [
        migrations.AddField(
            model_name='exammodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
