# Generated by Django 3.2.6 on 2021-10-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0043_notificationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumofferpackage',
            name='duration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
