# Generated by Django 3.2.6 on 2021-10-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0044_alter_premiumofferpackage_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='bronze_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='gold_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='is_bronze',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='is_gold',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='is_silver',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='silver_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
