# Generated by Django 3.2.6 on 2021-10-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0046_remove_premiumofferpackage_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
