# Generated by Django 3.2.6 on 2021-10-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0049_checkout_buyer_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawmodel',
            name='number',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='withdrawmodel',
            name='withdraw_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
