# Generated by Django 3.2.6 on 2021-10-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0050_auto_20211016_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawmodel',
            name='method',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.DeleteModel(
            name='WithDrawPaymentMethod',
        ),
    ]
