# Generated by Django 3.2.6 on 2021-10-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0052_alter_withdrawmodel_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawmodel',
            name='withdrawn',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='withdrawmodel',
            name='number',
            field=models.CharField(max_length=220, null=True),
        ),
    ]
