# Generated by Django 3.2.6 on 2021-10-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0055_alter_offer_offer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='is_submitted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
