# Generated by Django 3.2.6 on 2021-10-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0056_checkout_is_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='is_submitted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
