# Generated by Django 3.2.6 on 2021-10-18 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0058_checkout_order_submitted_is_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerpostrequest',
            name='all_post_seen',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
