# Generated by Django 3.2.6 on 2021-10-18 10:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0060_auto_20211018_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerpostrequest',
            name='seen_users',
            field=models.ManyToManyField(related_name='seen_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
