# Generated by Django 3.2.6 on 2021-10-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0062_checkout_order_is_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumofferpackage',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
