# Generated by Django 3.2.6 on 2021-10-19 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0063_premiumofferpackage_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmodel',
            name='orderId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.checkout'),
        ),
    ]
