# Generated by Django 3.2.6 on 2021-10-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0064_notificationmodel_orderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerpostrequest',
            name='seller_send_new_offer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
