# Generated by Django 3.2.6 on 2021-10-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0065_buyerpostrequest_seller_send_new_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerpostrequest',
            name='seller_send_new_offer',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
