# Generated by Django 3.2.6 on 2021-10-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0066_alter_buyerpostrequest_seller_send_new_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmodel',
            name='has_checked',
            field=models.BooleanField(default=False),
        ),
    ]
