# Generated by Django 3.2.6 on 2021-10-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0067_notificationmodel_has_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodel',
            name='has_checked',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
