# Generated by Django 3.2.6 on 2021-10-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0068_alter_notificationmodel_has_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='exammodel',
            name='has_checked',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
