# Generated by Django 3.2.6 on 2021-10-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0069_exammodel_has_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawmodel',
            name='is_new',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
