# Generated by Django 3.2.6 on 2021-10-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0072_offer_has_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmodel',
            name='title',
            field=models.CharField(max_length=220, null=True),
        ),
    ]
