# Generated by Django 3.2.6 on 2021-10-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0073_notificationmodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_pending',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
