# Generated by Django 3.2.6 on 2021-10-25 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0074_offer_is_pending'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewSellerModel',
        ),
    ]
