# Generated by Django 3.2.6 on 2021-10-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0075_delete_reviewsellermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='seo_title',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
