# Generated by Django 3.2.6 on 2021-10-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0077_manualpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualpayment',
            name='rec',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
