# Generated by Django 3.2.6 on 2021-10-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0078_manualpayment_rec'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualpayment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('DONE', 'DONE'), ('DECLINED', 'DECLINED')], default='PENDING', max_length=220),
        ),
    ]
