# Generated by Django 3.2.6 on 2021-10-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0079_manualpayment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualpayment',
            name='method',
            field=models.CharField(choices=[('BKASH', 'BKASH'), ('NAGAD', 'NAGAD')], max_length=220, null=True),
        ),
    ]
