# Generated by Django 3.2.6 on 2021-10-26 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0080_manualpayment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selleraccount',
            name='city',
        ),
    ]
