# Generated by Django 3.2.6 on 2021-10-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0081_remove_selleraccount_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.AddField(
            model_name='selleraccount',
            name='points',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
