# Generated by Django 3.2.6 on 2021-10-30 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0082_auto_20211030_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selleraccount',
            name='points',
        ),
    ]
