# Generated by Django 3.2.6 on 2021-10-30 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0083_remove_selleraccount_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='points',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
