# Generated by Django 3.2.6 on 2021-10-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0084_offer_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='already_clicked',
            field=models.BooleanField(default=False),
        ),
    ]
