# Generated by Django 3.2.6 on 2021-10-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0085_offer_already_clicked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='points',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
