# Generated by Django 3.2.6 on 2021-11-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0092_alter_offer_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignmodel',
            name='campaign_slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
