# Generated by Django 3.2.6 on 2021-11-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0095_submissionforcampaign_attend_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionforcampaign',
            name='attend_exam',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
