# Generated by Django 3.2.6 on 2021-12-15 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0100_alter_checkout_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualpayment',
            name='createa_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
