# Generated by Django 3.2.6 on 2021-12-15 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0101_manualpayment_createa_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manualpayment',
            old_name='createa_at',
            new_name='created_at',
        ),
    ]
