# Generated by Django 3.2.6 on 2021-10-31 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendemailtouser',
            name='receiver',
            field=models.CharField(max_length=220, null=True),
        ),
    ]
