# Generated by Django 3.2.6 on 2021-10-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0002_message_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='seen',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='seen',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
