# Generated by Django 3.2.6 on 2021-10-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0003_auto_20211004_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='msg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
